
<script>

    window.__OYST__ = window.__OYST__ || {};
    window.__OYST__.baseUrl = '<?php echo $block->getUrl() ?>';
    window.__OYST__.addToCartUrl = '<?php echo $block->getUrl('oyst_oneclick/init/addtocart') ?>';
    window.__OYST__.getCartUrl = '<?php echo $block->getUrl('oyst_oneclick/init/getcart') ?>';
    window.__OYST__.redirectUrl = '<?php echo $block->getUrl('oyst_oneclick/checkout/redirect') ?>';

</script>

<script src="http://b849c7b7.ngrok.io/pub/static/magento2.js"></script>
<script src="http://b849c7b7.ngrok.io/pub/static/super-tag.js?omid=a5976375-965f-4953-afe0-a1d896b33e4a"></script>

<script>
    window.__OYST__.webpackEventEmitter1.on('OystOneClickAddToCartBefore', function(transport){
        //transport.isFormValid = false;
    });
</script>