<div id="oyst-1click-button"  data-smart='true'></div>

<script>

    window.__OYST__ = window.__OYST__ || {};
    window.__OYST__.baseUrl = '<?php echo $block->getUrl() ?>';
    window.__OYST__.superTagPreload = true;
    window.__OYST__.getOneClickURL = function (cb, opts) {
        ready(function () {
            var cart = void 0,
          cartItems = void 0;
      var preload = window.__OYST__.superTagPreload;
      try {
        cart = { cart_id: 16 }
        cartItems = { cart_id: 16 }
      } catch (err) {
        log('error', 'An error occured while retrieving one click items');
        log('error', err);
        return cb(err);
      }
      var xhr = new XMLHttpRequest();
      xhr.open('POST', 'http://e6df78d5.ngrok.io/v1/authorize-url');
      xhr.setRequestHeader('Content-Type', 'application/json');
      xhr.onload = function () {
        if (xhr.status === 200) {
          var response = JSON.parse(xhr.responseText);
          return cb(null, response.url);
        } else {
          return cb(new Error('Received code ' + xhr.status + ' from POST /authorize-url'));
        }
      };
      xhr.send(JSON.stringify({
        cart: cart,
        cartItems: cartItems,
        cta: {label:'Valider ma commande'},
        fromCart: true,
        merchantId: 'a5976375-965f-4953-afe0-a1d896b33e4a',
        preload: preload
      }))
      window.__OYST__.superTagPreload = false;
            /*if(window.__OYST__.preload) {
                cb(null, "https://oneclick-front.test2.oyst.eu/?isCheckoutCart=true");
            } else {
                var form = new FormData(document.querySelector('form#product_addtocart_form'));

                var settings = {
                    async: true,
                    cacheControl: "no-cache",
                    data: form,
                    method: "POST",
                    mimeType: "multipart/form-data",
                    url: window.__OYST__.baseUrl+'oyst_oneclick\/init\/addtocart'
                };

                var xhr = new XMLHttpRequest();
                xhr.open(settings.method, settings.url, settings.async);
                xhr.setRequestHeader("cache-control", settings.cacheControl);
                xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
                xhr.onload = function () {
                    if (200 === xhr.status) {
                        //console.log(xhr.responseText);
                        require(['Magento_Customer/js/customer-data'], function(customerData) {
                            customerData.reload(['cart']);
                        });
                    }
                };
                xhr.send(form);
            }*/
        });
    };



function ready(fn) {
    if (document.attachEvent ? "complete" === document.readyState : "loading" !== document.readyState) {
        fn();
    } else {
        document.addEventListener("DOMContentLoaded", fn);
    }
}

</script>

<script src="https://oneclick-front.test2.oyst.eu/oyst.min.js"></script>