<?php if ($block->isEnabled()) : ?>

<script>

    window.__OYST__ = window.__OYST__ || {};
    window.__OYST__.baseUrl = '<?php echo $block->getUrl() ?>';
    window.__OYST__.addToCartUrl = '<?php echo $block->getUrl('oyst_oneclick/checkout/addtocart') ?>';
    window.__OYST__.getCartUrl = '<?php echo $block->getUrl('oyst_oneclick/checkout/getcart') ?>';
    window.__OYST__.successRedirectUrl = '<?php echo $block->getUrl('oyst_oneclick/checkout/redirect') ?>';
    window.__OYST__.failureRedirectUrl = '<?php echo $block->getUrl('checkout/cart') ?>';

</script>

<?php echo $block->getScriptTag(); ?>

<?php endif ?>
